# **TUGAS NUMPY 2026** 🧮

---
**Nama:**  Hubert Cendana

**NIM:**  245150207111049

Notebook ini berisi penugasan **NumPy** sebagai latihan lanjutan setelah workshop.

### Aturan singkat
- Kerjakan mandiri.
- Gunakan **NumPy** sebagai alat utama.
- Untuk soal yang berkaitan dengan masking, broadcasting, dan reshaping, usahakan **tidak menggunakan loop** jika memang bisa diselesaikan dengan operasi NumPy.
- Tulis jawaban langsung di cell yang sudah disediakan.


## **📦 Import Library**

Jalankan cell berikut terlebih dahulu.


In [1]:
import numpy as np

# Seed supaya hasil random konsisten
rng = np.random.default_rng(42)


## **📌 Soal 1: Membuat Array & Membaca Informasinya**

Buatlah array NumPy bernama `scores` dengan isi nilai berikut:

`[78, 85, 90, 66, 74, 88, 92, 81]`

Lalu tampilkan:
1. Isi array
2. Jumlah dimensi
3. Shape
4. Banyak elemen
5. Tipe data

**Hint:** gunakan `np.array`, lalu cek `ndim`, `shape`, `size`, dan `dtype`.


In [2]:
# Tulis jawabanmu di sini
arr = np.array([78, 85,90, 66, 74, 88, 92, 81])

print("1. Isi Array: ", arr)
print("2. Jumlah Dimensi: ", arr.ndim)
print("3. Bentuk Array: ", arr.shape)
print("4. Banyak Elemen: ", arr.size)
print("5. Tipe Data: ", arr.dtype)

1. Isi Array:  [78 85 90 66 74 88 92 81]
2. Jumlah Dimensi:  1
3. Bentuk Array:  (8,)
4. Banyak Elemen:  8
5. Tipe Data:  int64


## **📌 Soal 2: Factory Functions**

Gunakan fungsi bawaan NumPy untuk membuat:
1. Array `A` berukuran `3x4` yang seluruh elemennya `0`
2. Array `B` berukuran `2x3` yang seluruh elemennya `1`
3. Array `C` berukuran `3x3` yang seluruh elemennya `7`
4. Matriks identitas `D` berukuran `4x4`
5. Array `E` yang berisi 6 angka dari `0` sampai `1` dengan jarak sama rata

Tampilkan semua hasilnya.


In [4]:
# Tulis jawabanmu di sini
arrA = np.full((3, 4), 0)
arrB = np.full((2, 3), 1)
arrC = np.full((3, 3), 7)
arrD = np.eye(4)
arrE = np.linspace(0, 1, 6)

print("Array A:\n", arrA)
print("\nArray B:\n", arrB)
print("\nArray C:\n", arrC)
print("\nArray D:\n", arrD)
print("\nArray E:\n", arrE)

Array A:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Array B:
 [[1 1 1]
 [1 1 1]]

Array C:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array D:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array E:
 [0.  0.2 0.4 0.6 0.8 1. ]


## **📌 Soal 3: Indexing & Slicing**

Perhatikan array berikut:


In [5]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Dari array tersebut, tampilkan:
1. Elemen pada baris ke-2 kolom ke-3
2. Seluruh baris pertama
3. Seluruh kolom terakhir
4. Subarray 2x2 di tengah
5. Array hasil membalik urutan kolom pada semua baris

**Catatan:** gunakan indexing/slicing NumPy.


In [8]:
# Tulis jawabanmu di sini
print("1. Elemen pada baris ke-2 kolom ke-3:\n", arr[1,2])
print("\n2. Baris ke-1:\n", arr[0, ::])
print("\n3. Kolom ke-4:\n", arr[:, 3])
print("\n4. Sub-array baris 2-3 dan kolom 1-2:\n", arr[1:3, 1:3])
print("\n5. Array hasil membalik urutan kolom pada semua baris:\n", arr[:, ::-1])

1. Elemen pada baris ke-2 kolom ke-3:
 7

2. Baris ke-1:
 [1 2 3 4]

3. Kolom ke-4:
 [ 4  8 12 16]

4. Sub-array baris 2-3 dan kolom 1-2:
 [[ 6  7]
 [10 11]]

5. Array hasil membalik urutan kolom pada semua baris:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


## **📌 Soal 4: Boolean Masking & `np.where()`**

Diberikan array suhu berikut:


In [9]:
temps = np.array([29, 31, 35, 28, 33, 27, 30, 36, 32, 26])
print(temps)


[29 31 35 28 33 27 30 36 32 26]


Kerjakan hal berikut:
1. Ambil semua suhu yang **lebih dari 30**
2. Hitung berapa banyak suhu yang **lebih dari atau sama dengan 32**
3. Buat array label baru bernama `status` dengan aturan:
   - `"panas"` jika suhu > 32
   - `"normal"` jika suhu 29 s.d. 32
   - `"dingin"` jika suhu < 29

**Hint:** untuk poin (3), kamu bisa menggunakan `np.where()` bertingkat.


In [13]:
# Tulis jawabanmu di sini
bool_satu = temps > 30
bool_dua = temps >= 32

arr_status = np.where(temps > 32, "Panas", np.where(temps >= 29, "Normal", "Dingin"))
print("1. Ambil semua suhu yang lebih dari 30:\n", temps[bool_satu])
print("\n2. Hitung berapa banyak suku yang lebih dari atau sama dengan 32:\n", np.sum(bool_dua))
print("\n3. Buat array label baru dengan nama status dengan aturan:\n",arr_status)

1. Ambil semua suhu yang lebih dari 30:
 [31 35 33 36 32]

2. Hitung berapa banyak suku yang lebih dari atau sama dengan 32:
 4

3. Buat array label baru dengan nama status dengan aturan:
 ['Normal' 'Normal' 'Panas' 'Dingin' 'Panas' 'Dingin' 'Normal' 'Panas'
 'Normal' 'Dingin']


## **📌 Soal 5: View vs Copy**

Buat array berikut:


In [14]:
x = np.array([10, 20, 30, 40, 50, 60])
print(x)


[10 20 30 40 50 60]


Lalu lakukan:
1. Buat `view_part` dari elemen indeks 1 sampai 4 menggunakan slicing
2. Buat `copy_part` dari elemen indeks `[1, 2, 3, 4]` menggunakan advanced indexing
3. Ubah elemen pertama `view_part` menjadi `999`
4. Ubah elemen pertama `copy_part` menjadi `-100`
5. Tampilkan `x`, `view_part`, dan `copy_part`

Terakhir, tuliskan dengan singkat:
- mana yang menyebabkan array asli berubah?
- mana yang tidak?


In [15]:
# Tulis jawabanmu di sini
# Tambahkan penjelasan singkat dalam komentar juga.
view_part = x[1:5]
copy_part = x[[1, 2, 3, 4]]
view_part[0] = 999
copy_part[0] = -100
print("Array x:\n", x)
print("\nArray View:\n", view_part)
print("\nArray Copy:\n", copy_part)

Array x:
 [ 10 999  30  40  50  60]

Array View:
 [999  30  40  50]

Array Copy:
 [-100   30   40   50]


1. Yang menyebabkan array asli berubah adalah metode slicing karena metode slicing menggunakan reference dari array asli sehingga jika array copyan diubah maka array asli juga ikut berubah
2. Yang tidak menyebabkan array asli berubah adalah metode advanced indexing karena yang diambil hanya isi arraynya bukan referencenya

## **📌 Soal 6: Statistik Dasar & Missing Value (`NaN`)**

Gunakan array berikut:


In [16]:
values = np.array([12, 15, np.nan, 18, 21, np.nan, 24, 30])
print(values)


[12. 15. nan 18. 21. nan 24. 30.]


Tampilkan:
1. Rata-rata biasa dengan `np.mean()`
2. Rata-rata yang mengabaikan `NaN` dengan `np.nanmean()`
3. Standar deviasi yang mengabaikan `NaN` dengan `np.nanstd()`
4. Nilai minimum dan maksimum yang mengabaikan `NaN`

Lalu jelaskan singkat kenapa hasil `np.mean()` bisa berbeda dari `np.nanmean()`.


In [17]:
# Tulis jawabanmu di sini
print("1. Rata-rata biasa dengan np.mean:\n", np.mean(values))
print("\n2. Rata-rata dengan np.nanmean (mengabaikan NaN):\n", np.nanmean(values))
print("\n3. Standar deviasi yang mengabaikan NaN dengan np.nanstd:\n", np.nanstd(values))
print("\n4. Nilai minimum dan maksimum yang mengabaikan Nan:\n", np.nanmin(values), np.nanmax(values))

1. Rata-rata biasa dengan np.mean:
 nan

2. Rata-rata dengan np.nanmean (mengabaikan NaN):
 20.0

3. Standar deviasi yang mengabaikan NaN dengan np.nanstd:
 5.916079783099616

4. Nilai minimum dan maksimum yang mengabaikan Nan:
 12.0 30.0


**Penjelasan np.mean() dan np.nanmean()**

np.mean() dan np.nanmean() berbeda karena jika di dalam array terdapat nilai NaN dan kita menggunakan np.mean() biasa, maka hasil rata-ratanya akan menjadi nan sedangkan jika menggunakan np.nanmean() nilai NaN pada array tidak akan diikutkan pada proses perhitungan rata-rata nantinya sehingga bisa menghasilkan nilai rata-rata dalam bentuk numerik

## **📌 Soal 7: Broadcasting untuk Normalisasi**

Diberikan matriks fitur berikut:


In [18]:
X = np.array([
    [170, 65, 28],
    [165, 55, 24],
    [180, 75, 30],
    [175, 70, 29]
], dtype=float)

print(X)


[[170.  65.  28.]
 [165.  55.  24.]
 [180.  75.  30.]
 [175.  70.  29.]]


Anggap setiap kolom merepresentasikan fitur yang berbeda.  
Lakukan normalisasi z-score sederhana dengan rumus:

$$
Z = \frac{X - \text{mean kolom}}{\text{std kolom}}
$$

Tampilkan:
1. Mean per kolom
2. Std per kolom
3. Hasil normalisasi `Z`

**Hint:** gunakan `axis=0` dan manfaatkan broadcasting NumPy.


In [19]:
# Tulis jawabanmu di sini
arr_mean = np.mean(X, axis=0)
arr_std = np.std(X, axis=0)
X_normalized = (X - arr_mean) / arr_std
print("\nMean per kolom:\n", arr_mean)
print("\nStandard Deviation per kolom:\n", arr_std)
print("\nArray Normalized:\n", X_normalized)


Mean per kolom:
 [172.5   66.25  27.75]

Standard Deviation per kolom:
 [5.59016994 7.39509973 2.27760839]

Array Normalized:
 [[-0.4472136  -0.16903085  0.10976426]
 [-1.34164079 -1.52127766 -1.6464639 ]
 [ 1.34164079  1.18321596  0.98787834]
 [ 0.4472136   0.50709255  0.5488213 ]]


## **📌 Soal 8: Reshape & Mini Challenge**

Gunakan array 1 dimensi berikut:


In [20]:
z = np.arange(1, 25)
print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Kerjakan hal berikut:
1. Ubah `z` menjadi matriks berukuran `6x4`
2. Ubah hasilnya menjadi bentuk `3x2x4`
3. Ambil kembali seluruh data tersebut menjadi array 1 dimensi
4. Bonus: buat array window 4 elemen yang bergeser dari `z`, sehingga bentuk akhirnya menjadi:

`[[1,2,3,4], [2,3,4,5], ..., [21,22,23,24]]`

**Hint bonus:** boleh gunakan loop **atau** `sliding_window_view` jika kamu sudah tahu.


In [25]:
# Tulis jawabanmu di sini
arr_hsl = z.reshape(6,4)
arr_dua = arr_hsl.reshape(3,2,4)
arr_tiga = arr_dua.reshape(1,24)
arr_empat = np.lib.stride_tricks.sliding_window_view(z, window_shape=4)
print("1. Ubah z menjadi matriks berukuran 6x4:\n", arr_hsl)
print("\n2. Ambil hasilnya menjadi bentuk 3x2x4:\n", arr_dua)
print("\n3. Ambil kembali seluruh data tersebut menjadi array 1 dimensi:\n", arr_tiga)
print("\n4. Buat array window 4 elemen yang bergeser dari z:\n", arr_empat.tolist())

1. Ubah z menjadi matriks berukuran 6x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

2. Ambil hasilnya menjadi bentuk 3x2x4:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]

3. Ambil kembali seluruh data tersebut menjadi array 1 dimensi:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]

4. Buat array window 4 elemen yang bergeser dari z:
 [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14], [12, 13, 14, 15], [13, 14, 15, 16], [14, 15, 16, 17], [15, 16, 17, 18], [16, 17, 18, 19], [17, 18, 19, 20], [18, 19, 20, 21], [19, 20, 21, 22], [20, 21, 22, 23], [21, 22, 23, 24]]


# **🎯 Penutup**

Kalau kamu sudah menyelesaikan semua soal:
- cek lagi hasil outputmu,
- pastikan bentuk array dan logikanya sesuai,
- lalu simpan notebook ini sebelum dikumpulkan.

Semangat! 🚀
